name: 'Deploy docs and benchmarks to GitHub pages'

on:
  push:
    branches-ignore:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout benchmark repo
        uses: actions/checkout@v2
        with:
          repository: blinkkcode/amagaki-benchmark
          path: amagaki-benchmark
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache benchmark node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-bm
        with:
          path: amagaki-benchmark/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('amagaki-benchmark/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Build docs and benchmark build
        run: |
                npm install --dev
                npm run dev:start
                npm run docs
                cd amagaki-benchmark
                npm install
                node ../dist/src/index.js build
      - name: Process benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Amagaki profiling benchmark
          tool: 'benchmarkjs'
          output-file-path: amagaki-benchmark/build/.amagaki/benchmark.txt
          # Push and deploy GitHub pages branch automatically
          benchmark-data-dir-path: docs/benchmark
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
