name: Build example site benchmark

on:
  push:
    branches-ignore:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
            ./cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build example site
        run: |
                npm install
                npm run dev:start
                node ./dist/src/index.js build example
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Amagaki profiling benchmark
          tool: 'benchmarkjs'
          output-file-path: example/build/.amagaki/benchmark.txt
          external-data-json-path: ./cache/benchmark-data.json
          # PR commenting and failure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          comment-on-alert: true