name: 'Deploy docs and benchmarks to GitHub pages'

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout benchmark repo
        uses: actions/checkout@v2
        with:
          repository: blinkk/amagaki-benchmark
          path: amagaki-benchmark
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache benchmark node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-bm
        with:
          path: amagaki-benchmark/node_modules
          key: ${{ runner.os }}-build-bm-${{ env.cache-name }}-${{ hashFiles('amagaki-benchmark/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-bm-${{ env.cache-name }}-
      - name: Prepare for docs.
        run: |
            mkdir -p ./public/
            npm install --dev
      - name: Build website
        run: |
            cd website/
            npm ci
            npm run build
            cp -r build/* ../public/
            echo "amagaki.dev" > ../public/CNAME
      - name: Build docs
        run: |
            rm -fr ./public/api
            npm run docs:ci
      - name: Build benchmark build
        run: |
            # Preserve benchmark files, otherwise the gh-pages action will overwrite them.
            mkdir -p public/benchmark
            curl https://raw.githubusercontent.com/blinkk/amagaki/gh-pages/benchmark/data.json --output public/benchmark/data.json
            curl https://raw.githubusercontent.com/blinkk/amagaki/gh-pages/benchmark/index.html --output public/benchmark/index.html

            # Build the benchmark repository.
            node ./dist/src/cli.js --profile build amagaki-benchmark
      - name: Process benchmark results
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Amagaki profiling benchmark
          tool: 'benchmarkjs'
          output-file-path: amagaki-benchmark/build/.amagaki/benchmark.txt
          # Output the processed data to the benchmark directory.
          benchmark-data-dir-path: public/benchmark
          external-data-json-path: public/benchmark/data.json
          max-items-in-chart: 50
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
