name: Build example site benchmark

on:
  push:
    # branches:
    # - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout benchmark repo
        uses: actions/checkout@v2
        with:
          repository: blinkkcode/amagaki-benchmark
          path: benchmark
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cache benchmark node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-benchmark
        with:
          path: |
            ~/.npm
            benchmark/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('benchmark/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Build amagaki
        run: |
                npm install
                npm run dev:start
                cd benchmark
                npm install
                node ../dist/src/index.js build
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Amagaki profiling benchmark
          tool: 'benchmarkjs'
          output-file-path: benchmark/build/.amagaki/benchmark.txt
          # Push and deploy GitHub pages branch automatically
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true