name: 'Release Please'
on:
  push:
    branches:
      - main
jobs:

  release-please-amagaki:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/amagaki/
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          command: manifest
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs['packages/amagaki--release_created'] }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs['packages/amagaki--release_created'] }}
      - run: npm install
        if: ${{ steps.release.outputs['packages/amagaki--release_created'] }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs['packages/amagaki--release_created'] }}

  release-please-amagaki-engine-preact:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/amagaki-engine-preact/
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          command: manifest
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs['packages/amagaki-engine-preact--release_created'] }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs['packages/amagaki-engine-preact--release_created'] }}
      - run: npm install
        if: ${{ steps.release.outputs['packages/amagaki-engine-preact--release_created'] }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs['packages/amagaki-engine-preact--release_created'] }}
