name: 'Release Please'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm install
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm publish -w packages/amagaki
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs['packages/amagaki--release_created'] }}
      - run: npm publish -w packages/amagaki-engine-preact
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs['packages/amagaki-engine-preact--release_created'] }}
      - run: npm publish -w packages/amagaki-plugin-page-builder
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs['packages/amagaki-plugin-page-builder--release_created'] }}
