name: "Run tests"
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run npm tests
        run: |
          npm install -w packages/amagaki
          npm install
          npm test --workspaces
      - name: Run external tests
        working-directory: packages/amagaki/tests
        run: |
          ./runAll.sh
      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
