name: "Run tests"
on:
  workflow_dispatch:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Run npm tests
        run: |
          npm install
          npm test --workspaces
      - name: Run external tests
        working-directory: packages/amagaki/tests
        run: |
          ./runAll.sh
